### ISSUE TITLE
Where I can find the document of java of tensorflow?

### ISSUE THREAD

**Issue by cgpeter96** [tensorflow/java#141]
Recently, I wanna use java deploy my model. But some thing wrong happen.  Such as  `tensorflow core dump` in libtensorflow-1.15.0.so. 
SO, I wanna change the my java library to `tensorflow/java`, but I cannot find some document to help quickly load my model. The only thing which can help me is the `Issues`.

And when I test my code in tensorflow-core-api, it raise the 
```
Warning: Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnitensorflow in java.library.path
```

where I can found that.

Thanks for help~

**Comment by karllessard** [comment]
Hi @cgpeter96 , maybe you can look at [these examples](https://github.com/tensorflow/java-models/tree/master/tensorflow-examples)? 

Also make sure that you include a dependency to a native artifact (e.g. `org.tensorflow:tensorflow-core-api:0.2.0:linux-x86_64`) or even better, depend on the `org.tensorflow:tensorflow-core-platform` instead of `tensorflow-core-api`, so that all native artifacts are automatically added to your project for you

**Comment by karllessard** [comment]
The TensorFlow website also have instructions for [installing TF Java](https://www.tensorflow.org/install/lang_java), plus a running example

**Comment by cgpeter96** [comment]
> The TensorFlow website also have instructions for [installing TF Java](https://www.tensorflow.org/install/lang_java), plus a running example

Thank you for help 👍.

**Comment by yl1994yl** [comment]
@cgpeter96 I have met the same problem, can u tell me how to solve it? Thanks.
