### ISSUE TITLE
DataType.of should be non case sensitive

### ISSUE THREAD

**Issue by rnett** [tensorflow/java#145]
Currently `DataType.of` only accepts uppercase names like `FLOAT32`.  Anyone used to using python will expect `float32` and similar lowercase names to work.  It seems like it may have been a design decision by it's inclusion in the docs, but I don't see a reason not to add it (probably as a toUppercase on the arg rather than extra cases) and I expect almost everyone will run into this at some point.

**Comment by rnett** [comment]
This will likely be closed by #139

**Comment by karllessard** [comment]
Hi @rnett , I was about to say so, SIG JVM have agreed to go forward with #139, which leverages even more Java idiomatic type features in preference to a custom or pythonic type system. 

I suggest we close this issue so that you can continue to provide your valuable feedbacks on the next PRs to come that will be related to this

**Comment by rnett** [comment]
Agreed.
